### ISSUE TITLE
[v3] Max of 1 award is showing under avatar

### ISSUE THREAD

**Issue by dyn0** [Spuds/SMF-Member-Awards#18]
Have assigned multiple awards to myself and have tried many different values for "Awards in Post"... still only able to display 1 award.  

The funny thing is, I do remember when first setting awards v3 up we were only able to display max of 2.  Now, however, no matter what settings we use it will not go higher than 1.

**Comment by Spuds** [comment]
can not reproduce in current mod, must have been fixed along the way
