### ISSUE TITLE
 Fatal error: Cannot redeclare template_awards()

### ISSUE THREAD

**Issue by motahhari** [Spuds/SMF-Member-Awards#39]
Hi
In profiles when click on awards list , I get this error:
 Fatal error: Cannot redeclare template_awards() (previously declared in /home/smpd/public_html/forum/Themes/AVS5/Profile.template.php:3254) in /home/smpd/public_html/forum/Themes/default/AwardsProfile.template.php on line 110

**Comment by Spuds** [comment]
caused by an old template modification that was done before the template was pulled into its own file.  Remove any edits to profile.template
