### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by jeroenla** [Spuds/SMF-Member-Awards#42]
Hi,
About a year ago, I got this working. But now again, I cannot get the thing installed. I pulled the zip from here: https://github.com/Spuds/SMF-Member-Awards

But SMF won't let me upload it, saying the package is empty (it is 88kb) or the folders aren't writable (they are)...

Can I get a step-by-step instruction manual please?

**Comment by Spuds** [comment]
Not sure if thats due to the zip file that github created .. try the file from here
https://github.com/Spuds/SMF-Member-Awards/releases/download/3.0.0/SMF-Member-Awards-master.zip

**Comment by jeroenla** [comment]
That one does actually help :) Thanks.

**Comment by jeroenla** [comment]
In the core theme it does actually work, but not in the theme I have used before (and where it used to work)

**Comment by Spuds** [comment]
When you installed it should have "offered" to install in other themes (if it was able to find the edit locations in the custom theme).  If not then you will have to manually edit the display template theme file.  The edits will be these: https://github.com/Spuds/SMF-Member-Awards/blob/master/install_display_template.xml

If you are not comfortable doing that, create a gist with that file and I'll make the edits for you

**Comment by Spuds** [comment]
No reply
