### ISSUE TITLE
Database Issue.

### ISSUE THREAD

**Issue by SychO9** [Spuds/SMF-Member-Awards#43]
Greetings, For some reason whenever I delete an Award this appears when viewing topics :/ 
How can I fix this knowing that I made no changes to the mod.

Thanks in Advance.

```
Duplicate entry '1-3' for key 'id_member_id_award'
File: /home/****/****/****/***.**.**/htdocs/forum/Sources/AwardsManage.php
Line: 350

```

**Comment by SychO9** [comment]
anyone ? :/ pls

**Comment by Spuds** [comment]
Do you have access to phpmyadmin on your install ?

The message indicates that the member id 1, which is probably the admin?  has an award 3 already assigned and its trying to add it again ... the code should prevent that so I don't really know why its doing it, certainly a bug.

If you have access to phpmyadmin, open the table awards_members and sort on member_id col ... see if user '1' has any award_id 3 row, and if so delete those rows.

**Comment by SychO9** [comment]
empty there is nothing in smf_awards :/

**Comment by SychO9** [comment]
i keep deleting that row and every time i refresh my awards page in my profile it fills back o.O

**Comment by SychO9** [comment]
same issue appears every time adding an auto assign award and then removing it, it just stays in the database cause the error to show.

**Comment by Spuds** [comment]
Just for user with an id of 1 ?

**Comment by SychO9** [comment]
well since i am testing the mod in a separate forum which has one member only which is me, then yes
