### ISSUE TITLE
Database error, table doesn't exist

### ISSUE THREAD

**Issue by tim0teo** [Spuds/SMF-Member-Awards#44]
Hello Spud,

I had found your SMF Mod, the only one Awards actualy working for SMF, and it was working fine, until i started to add Awards for Achievements.

I have a database error selecting Topic Count, i don't know if the other achievements option have the same problem. It seems topic count table doesn't exist, i get this error message trying to access to a Profile.

`Table 'b14_19476507_s125.smf_topics' doesn't exist
File: .../Sources/AwardsManage.php
Line: 410`

My programming knowledge is very poor, and i will aprreciate your assistance solving this error.

Even there is another issue which another person asked some time ago, the awards miniatures doesn't show in Profile Post, only the small icon to go to the list of Awards earned. But this is a minor problem for me, i would be confortable that way, maybe too many icons in Profile Post with time.

Please, help me with the database error when you have some spare time.

Thanks in advance.

**Comment by Spuds** [comment]
If you can, please edit that file ```/Sources/AwardsManage.php```doing the following.

On line 402 it says ```FROM smf_topics``` change it to be ```FROM {db_prefix}smf_topics``` and see if that fixes that issue.   

Not sure about the icon issue, I may just not have added them there!

**Comment by tim0teo** [comment]
Hello Spud,

As I said, if the small icon awards doesn't show in user profile in message i can go ahead with that, mostly if the function is not added.

Thanks for the tip because it worked with the database problem, now there is not error trying to access to a user profile with Topic Count enabled for an Award.

But i have fund adding more Awards a weird thing. There are two options for Users to Request an Award, or to Assign an Award to other Users.

I have set the permission for all Users to Manage and to Request awards, however thos awards i've set as Assignable, i can't see an icon to go to assign that avatar to a User, and as Admin i should, but with a Regular User account neither shows an icon to assign award. I'm a bit lost here.

**Comment by tim0teo** [comment]
Hello Spud,

Casualty searching for the problem of assign awards not showing, i have found in SMF Forums the code to show the awards in poster profile, and it worked. It was not a must for me, but isn't bad as well hehe.

But I really would like your help why the assign awards doesn't show even with all permissions given.

Thank you.

**Comment by Spuds** [comment]
fixed in https://github.com/Spuds/SMF-Member-Awards/commit/42b5c264cb2947eb9bd403f1e3ff057e3ef32d3b
