### ISSUE TITLE
how to set a max/min badge image size?

### ISSUE THREAD

**Issue by eskiee** [Spuds/SMF-Member-Awards#46]
i'd like to set a max/min badge image restriction as they appear below the users' avatars. i ask this because i intend to let members freely create/distribute their own badges, and they definitely need a built-in size restriction.

**Comment by Spuds** [comment]
I don't think there is a unique class associated with those icons,  TBH one should be added but .... so anyway you can target and restrict the image in that area with some CSS.

For example this should work (add it your themes index.css) for the below profile award images (untested, I don't currently have an SMF install to check)  The 100px is just an example, use what you want.
``
.poster > ul > li > fieldset > a > img {
  max-width:100px;
  max-height:100px;
  width: auto;
  height: auto;
}
```

**Comment by Spuds** [comment]
no response, assumed this worked.
