### ISSUE TITLE
Error Making New Award

### ISSUE THREAD

**Issue by derekstephen** [Spuds/SMF-Member-Awards#47]
While trying to create a new award, when I press "Save Award"  I get this error below.

> Field 'filename' doesn't have a default value
> File: /home/vhosts/epsilon.tf/epsilon.tf/Sources/AwardsSubs.php
> Line: 394

Any ideas?

**Comment by barandasdemir** [comment]
Having the same problem with the latest version, how did you solve this issue @derekstephen ?
