### ISSUE TITLE
!A little fix with $smcFunc in AwardsSubs.php

### ISSUE THREAD

**Issue by tuivodich** [Spuds/SMF-Member-Awards#49]
Hi Spuds!
I tried your mod for SMF2.1 on my localhost. It works fine but it has an error when I add new category or award:  `An error has occurred: Primary Key field missing in insert call `

So I checked **AwardsSubs.php** file and change a little bit:
Line 371: `$smcFunc['db_insert']('replace', '{db_prefix}awards',` change to `$smcFunc['db_insert']('insert', '{db_prefix}awards',`
Line 1070: `$smcFunc['db_insert']('replace',` change to `$smcFunc['db_insert']('insert',`
And now it works!
So please check this and fix a little bit, correct me if I'm wrong! Sorry for my bad English!

**Comment by Spuds** [comment]
Going to close this as the mod is currently only for SMF 2.0 and, this is a 2.1 incompatibly.  I'm sure there are many more and 2.1 has changed more since this was opened.  Will need a full "redo"
