### ISSUE TITLE
!Fixing error log with create_function() in PHP 7.2

### ISSUE THREAD

**Issue by tuivodich** [Spuds/SMF-Member-Awards#51]
Hello, I tested this mod in PHP 7.2 and it showed error log with create_function() defined in **AwardsAdmin.php**. So I changed a little bit to compatial with PHP 7.2:

In **AwardsAdmin.php**:
- **Line 209 - 224:** Find:

> 						'function' => create_function('$row', '
> 							global $txt, $settings;
> 
> 							$result = ((allowedTo(\'manage_awards\')) ? \'<a href="\' . $row[\'edit\'] . \'" title="\' . $txt[\'awards_button_edit\'] . \'"><img src="\' . $settings[\'images_url\'] . \'/awards/modify.png" alt="" /></a>
> 										<a href="\'  . $row[\'delete\'] . \'" onclick="return confirm(\\\'\' . $txt[\'awards_confirm_delete_award\'] . \'\\\');" title="\' . $txt[\'awards_button_delete\'] . \'"><img src="\' . $settings[\'images_url\'] . \'/awards/delete.png" alt="" /></a>
> 										<br />\' : \'\');
> 
> 							if (($row[\'award_type\'] <= 1) && (allowedTo(\'manage_awards\') || (allowedTo(\'assign_awards\') && !empty($row[\'assignable\']))))
> 								$result .= \'
> 										<a href="\' . $row[\'assign\'] . \'" title="\' . $txt[\'awards_button_assign\'] . \'"><img src="\' . $settings[\'images_url\'] . \'/awards/assign.png" alt="" /></a>\';
> 
> 							$result .= \'
> 										<a href="\' . $row[\'view_assigned\'] . \'" title="\' . $txt[\'awards_button_members\'] . \'"><img src="\' . $settings[\'images_url\'] . \'/awards/user.png" alt="" /></a>\';
> 
> 							return $result;'
> 						),

Replace with:

> 						'function' => function($row) {
> 							global $txt, $settings;
> 
> 							$result = ((allowedTo('manage_awards')) ? '<a href="' . $row['edit'] . '" title="' . $txt['awards_button_edit'] . '"><img src="' . $settings['images_url'] . '/awards/modify.png" alt="" /></a>
> 										<a href="'  . $row['delete'] . '" onclick="return confirm(\'' . $txt['awards_confirm_delete_award'] . '\');" title="' . $txt['awards_button_delete'] . '"><img src="' . $settings['images_url'] . '/awards/delete.png" alt="" /></a>
> 										<br />' : '');
> 
> 							if (($row['award_type'] <= 1) && (allowedTo('manage_awards') || (allowedTo('assign_awards') && !empty($row['assignable']))))
> 								$result .= '
> 										<a href="' . $row['assign'] . '" title="' . $txt['awards_button_assign'] . '"><img src="' . $settings['images_url'] . '/awards/assign.png" alt="" /></a>';
> 
> 							$result .= '
> 										<a href="' . $row['view_assigned'] . '" title="' . $txt['awards_button_members'] . '"><img src="' . $settings['images_url'] . '/awards/user.png" alt="" /></a>';
> 
> 							return $result;
> 						},

- **Line 712 - 718**: Find:

> 					'function' => create_function('$rowData', '
> 						global $scripturl;
> 
> 						if ($rowData["id_member"] > 0)
> 							return \'<a href="\' . strtr($scripturl, array(\'%\' => \'%%\')) . \'?action=profile;u=\' . $rowData[\'id_member\'] . \'">\' . $rowData[\'member_name\'] . \'</a>\';
> 						return $rowData["member_name"];
> 					'),

Replace with:

> 					'function' => function($rowData) {
> 						global $scripturl;
> 
> 						if ($rowData["id_member"] > 0)
> 							return '<a href="' . strtr($scripturl, array('%' => '%%')) . '?action=profile;u=' . $rowData['id_member'] . '">' . $rowData['member_name'] . '</a>';
> 						return $rowData["member_name"];
> 					},

**Comment by jsqx** [comment]
@Spuds 

Can you adapt this modification for PHP 7.2 / 7.3?

**Comment by tuivodich** [comment]
> @Spuds
> 
> Can you adapt this modification for PHP 7.2 / 7.3?

I tested this mod for PHP 7.2/7.3, it works ok!

**Comment by jsqx** [comment]
Thanks for the information.

**Comment by Spuds** [comment]
Create function removed/updated.   see https://github.com/Spuds/SMF-Member-Awards/issues/56 for details
