### ISSUE TITLE
The awards did not appear.

### ISSUE THREAD

**Issue by Aurydevelopment** [Spuds/SMF-Member-Awards#54]
Default theme is fine but rewards do not appear in the theme I edited. Most likely because of horizontal postbit. Can anyone help?

![Screenshot_5](https://user-images.githubusercontent.com/64798519/153753130-e39ba54f-ae54-487d-9422-53a0a0dcdbd5.png)

**Comment by Spuds** [comment]
Check the commends in file ```[install_display_template.xml](https://github.com/Spuds/SMF-Member-Awards/blob/master/install_display_template.xml)``` its likely those edits could not be found due to the custom theme.  You will have to manually add those in your theme,

**Comment by Spuds** [comment]
No response, closing
