### ISSUE TITLE
Field 'filename' doesn't have a default value   Line: 394  Sources/AwardsSubs.php

### ISSUE THREAD

**Issue by RASPUTIN-crypto** [Spuds/SMF-Member-Awards#55]
Please can someone help me fix this ??   Field 'filename' doesn't have a default value   Line: 394  Sources/AwardsSubs.php

**Comment by Spuds** [comment]
fixed in https://github.com/Spuds/SMF-Member-Awards/commit/0135593f73f9f1950efabcb6c26016e8ebcd8281
