### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by BodzioXs** [Spuds/SMF-Member-Awards#56]
Hi,
I guess after updating PHP to 8.0 I have some issues with this mod. Could you help me with them?

Error:
https://i.imgur.com/QVO676c.png
Log:
https://i.imgur.com/aB78tRg.png
When I want to edit category:
https://i.imgur.com/xxngPFr.png
Log:
https://i.imgur.com/lSahiFe.png

Any idea what could be wrong?
Thanks for help.

**Comment by Spuds** [comment]
Those are all php8.x related issues.  The SMF branch has not been updated in sometime in favor of the elkarte branch.  I'll try to at least get these errors cleaned up, but it will be a couple of days.

**Comment by BodzioXs** [comment]
Thank you very much. The mod works even with these errors because I managed to create a new reward and sign to it some users but it would be nice to get rid of them.

Btw. great mod!

**Comment by Spuds** [comment]
Moslty closed in https://github.com/Spuds/SMF-Member-Awards/commit/8935d7b5b35003b8df8593ecee71061290704107 and https://github.com/Spuds/SMF-Member-Awards/pull/57/commits/66bde461864413a7bf8c0bfb8f8911ccb5b94064
